export const sections = [
    {
        id: 1,
        name: 'Executive Summary',
        icon: 'custDetails',
        expandable: false,
        formData: [
            {
                name: 'Compass Case No.',
                type: 'text',
                value: '119459',
            },
            {
                name: 'Scenario(s) Breached',
                type: 'text',
                value: '1',
            },
            {
                name: 'Description of Breached Scenario(s)',
                type: 'textarea',
                value: 'CASH_DEP_CAA_DAILY_L',
            },
            {
                name: 'Is Bank Employee',
                type: 'radio',
                value: 'Yes',
                options: ['Yes', 'No', 'Unknown'],
            },
        ],
        summaryDetails: [
            'CASH_DEP_CAA_DAILY_1',
            'KUSUM BALA W/O ASHOK KUMAR',
            '50230100000133',
            '1',
            '1',
            'does not have',
            'High',
        ],
        header: true,
        type: 'header',
        hasForm: true,
        hasGraph: false,
        graph: null,
        graphList: null,
    },

    {
        id: 2,
        name: 'Customer Details (KYC)',
        icon: 'custDetails',
        expandable: true,
        type: 'form',
        hasGraph: false,
        hasFrom: true,
        hasTable: false,
        formData: [
            {
                name: 'Customer Name',
                type: 'text',
                value: 'Burhanuddin Patrawala',
            },
            {
                name: 'Customer Risk Rating',
                type: 'text',
                value: 'High',
            },
            {
                name: 'Account Risk Rating',
                type: 'text',
                value: 'Medium',
            },
            {
                name: 'Customer Type',
                type: 'text',
                value: 'VVIP',
            },
            {
                name: 'KYC last Update Date',
                type: 'text',
                value: '11/08/2022',
            },
            {
                name: 'Occupation',
                type: 'text',
                value: 'Minister',
            },
            {
                name: 'Nature Of Business',
                type: 'text',
                value: 'Heavy Transport',
            },
        ],
        graph: null,
        graphList: null,
    },

    {
        id: 3,
        name: 'Real-Time Screening',
        icon: 'rtScreening',
        expandable: true,
        type: 'component',
        componentType: 'rtScreening',
        hasGraph: true,
        hasForm: true,
        formData: [
            {
                name: 'Name',
                value: 'Burhanuddin Patrawala',
                type: 'text',
            },
            {
                name: 'Other Names',
                value: '',
                type: 'text',
            },
            {
                name: 'Date of Birth',
                value: '',
                type: 'date',
            },
            {
                name: 'Account Number',
                value: '502301000000133',
                type: 'text',
            },
            {
                name: 'Customer ID',
                value: '610358304',
                type: 'text',
            },
            {
                name: 'Passport Number',
                value: '',
                type: 'text',
            },
            {
                name: 'Tax ID Number',
                value: '',
                type: 'text',
            },
            {
                name: 'Aadhaar Number',
                value: '',
                type: 'text',
            },
            {
                name: 'Voter ID Number',
                value: '',
                type: 'text',
            },
            {
                name: 'PAN Number',
                value: '',
                type: 'text',
            },
            {
                name: 'Address',
                value: '',
                type: 'textarea',
            },
        ],
        hasTable: false,
        graph: 'PIE',
        graphList: ['PIE'],
    },

    {
        id: 4,
        name: 'Transaction Details',
        icon: 'transaction',
        expandable: true,
        type: 'graph',
        hasGraph: true,
        hasForm: false,
        hasTable: true,
        graph: 'PIE',
        grpahList: ['PIE'],
    },

    {
        id: 5,
        name: 'Alert Details',
        icon: 'actionItem',
        expandable: true,
        type: 'text',
        hasGraph: false,
        hasForm: false,
        hasTable: true,
        graph: null,
        graphList: null,
        sectionData: [],
    },

    {
        id: 6,
        name: 'Account Profile (Past 6 months)',
        icon: 'accountProfile',
        expandable: true,
        type: 'form',
        hasGraph: false,
        hasForm: true,
        hasTable: false,
        graph: null,
        formData: [
            {
                name: 'Products Used',
                type: 'text',
                value: 'SB112',
            },
            {
                name: 'Total Debit',
                type: 'text',
                value: '0',
            },
            {
                name: 'Total Debit Count',
                type: 'text',
                value: '0',
            },
            {
                name: 'Total Credit',
                type: 'text',
                value: '24000',
            },
            {
                name: 'Total Credit Count',
                type: 'text',
                value: '12',
            },
            {
                name: 'Account Risk',
                type: 'text',
                value: 'High',
            },
            {
                name: 'Risk last changed',
                type: 'date',
                value: '18/01/2013',
            },
            {
                name: 'Last 5 Account Activities',
                type: 'textarea',
                value: '',
            },
            {
                name: 'Past CTR or SR or other Regulatory Reports in this account/customer',
                type: 'radio',
                value: 'No',
                options: ['Yes', 'No'],
            },
            {
                name: 'If Yes, Count',
                type: 'text',
                value: '',
            },
            {
                name: 'If Yes, Date',
                type: 'date',
                value: '',
            },
        ],
    },

    {
        id: 7,
        name: 'Links',
        icon: 'links',
        expandable: true,
        type: 'form',
        hasGraph: false,
        hasFrom: true,
        hasTable: false,
        formData: [
            {
                name: 'From Date',
                type: 'text',
                value: '11/08/2022',
            },
            {
                name: 'To Date',
                type: 'text',
                value: '18/08/2022',
            },
            {
                name: 'Account No.',
                type: 'text',
                value: '303353508742',
            },
            {
                name: 'Level Count',
                type: 'text',
                value: '5',
            },
        ],
        graph: null,
        graphList: null,
    },

    {
        id: 8,
        name: 'Past History',
        icon: 'pastHistory',
        expandable: true,
        type: 'graph',
        hasGraph: true,
        hasFrom: false,
        hasTable: false,
        graph: 'SCATTER',
        graphList: ['SCATTER'],
    },

    {
        id: 9,
        name: 'Related Parties',
        icon: 'relatedParties',
        expandable: true,
        type: 'form',
        hasGraph: false,
        hasFrom: true,
        hasTable: false,
        formData: [
            {
                name: 'Lorem Ipsum',
                type: 'text',
                value: '',
            },
            {
                name: 'Lorem Ipsum',
                type: 'text',
                value: '',
            },
            {
                name: 'Lorem Ipsum',
                type: 'text',
                value: '',
            },
            {
                name: 'Lorem Ipsum',
                type: 'text',
                value: '',
            },
        ],
        graph: null,
        graphList: null,
    },

    {
        id: 10,
        name: 'Ringside View',
        icon: 'ringsideView',
        expandable: true,
        type: 'graph',
        hasGraph: true,
        hasForm: false,
        hasTable: false,
        graph: 'BAR3D',
        graphList: ['PIE', 'PIE', 'BAR'],
        summaryDetails: ['', '', '', ''],
    },

    {
        id: 11,
        name: 'Customer Case History',
        icon: 'summaryDetails',
        expandable: true,
        type: 'table',
        hasGraph: false,
        hasFrom: false,
        hasTable: true,
        graph: null,
        graphList: null,
    },

    {
        id: 12,
        name: 'Email Exchange',
        icon: 'email',
        expandable: true,
        type: 'form',
        hasGraph: false,
        hasFrom: true,
        hasTable: false,
        formData: [
            {
                name: 'Compose',
                type: 'button',
                function: 'modal',
                modalType: 'compose',
                value: 'Compose',
            },
            {
                name: 'Inbox',
                type: 'button',
                function: 'modal',
                modalType: 'inbox',
                value: 'Inbox (12 Unread)',
            },
            {
                name: 'Sent',
                type: 'button',
                function: 'sent',
                value: 'Sent',
            },
        ],
        graph: null,
        graphList: null,
    },

    {
        id: 13,
        name: 'View Comment For Case',
        icon: 'viewComments',
        expandable: true,
        type: 'text',
        hasGraph: false,
        hasFrom: true,
        hasTable: false,
        graph: null,
        graphList: null,
        sectionData: [
            'System - 121012 - 11/May/2022 08:08',
            'System - 121012 - 11/May/2022 08:08',
            'AMLUser - 121012 - 11/May/2022 08:08',
            'AMLUser - 121012 - 11/May/2022 08:08',
            'AMLUser - 121012 - 11/May/2022 08:08',
            'AMLUser - 121012 - 11/May/2022 08:08',
        ],
    },
    {
        id: 14,
        name: 'Add/View EDD',
        icon: 'viewEdd',
        expandable: true,
        type: 'form',
        hasGraph: false,
        hasFrom: true,
        hasTable: false,
        formData: [
            {
                name: 'addEdd',
                type: 'button',
                function: 'addEdd',
                value: 'Add EDD',
            },
            {
                name: 'viewEdd',
                type: 'button',
                function: 'viewEdd',
                value: 'View EDD',
            },
        ],
        graph: null,
        graphList: null,
    },

    {
        id: 15,
        name: 'View Attach Case Evidence',
        icon: 'attach',
        expandable: true,
        type: 'upload',
        hasGraph: false,
        hasFrom: false,
        hasTable: false,
        graph: null,
        graphList: null,
    },
]

export const pages = [
    {
        id: 1,
        title: 'ViewSTR',
        menu: [
            'Indian STR - ARF',
            'Indian STR - TRF',
            'SL STR',
            'UK SAR',
            'Maldives STR',
            'Nepal STR',
            'Seychelies STR',
            'Singapore STR',
            'USA SAR',
            'Kenya SAR',
            'Maurite STR',
            'Zambie STR',
        ],
    },
    {
        id: 2,
        title: 'Button 2',
        menu: ['SubButton1', 'SubButton2', 'SubButton3'],
    },
    {
        id: 3,
        title: 'Button 3',
        menu: ['SubButton1', 'SubButton2', 'SubButton3'],
    },
]

export const chartConfig = [
    {
        type: 'SCATTER',
        option: {
            title: {
                text: 'Top Performing Securities',
                subtext: 'September 2019',
            },
            xAxis: {},
            yAxis: {},
            tooltip: {
                position: 'top',
            },
            series: [
                {
                    symbolSize: 10,
                    data: [
                        [10.0, 8.04],
                        [8.07, 6.95],
                        [13.0, 7.58],
                        [9.05, 8.81],
                        [11.0, 8.33],
                        [14.0, 7.66],
                        [13.4, 6.81],
                        [10.0, 6.33],
                        [14.0, 8.96],
                        [12.5, 6.82],
                        [9.15, 7.2],
                        [11.5, 7.2],
                        [3.03, 4.23],
                        [12.2, 7.83],
                        [2.02, 4.47],
                        [1.05, 3.33],
                        [4.05, 4.96],
                        [6.03, 7.24],
                        [12.0, 6.26],
                        [12.0, 8.84],
                        [7.08, 5.82],
                        [5.02, 5.68],
                    ],
                    type: 'scatter',
                },
            ],
        },
    },
    {
        type: 'PIE',
        option: {
            tooltip: {
                trigger: 'item',
            },
            legend: {
                top: '5%',
                left: 'center',
            },
            series: [
                {
                    name: 'Access From',
                    type: 'pie',
                    radius: ['40%', '70%'],
                    avoidLabelOverlap: false,
                    label: {
                        show: false,
                        position: 'center',
                    },
                    //   emphasis: {
                    //       label: {
                    //           show: true,
                    //           fontSize: '40',
                    //           fontWeight: 'bold',
                    //       },
                    //   },
                    labelLine: {
                        show: false,
                    },
                    data: [
                        {
                            value: 750,
                            name: 'Search Engine',
                            itemStyle: {
                                color: '#ffc600',
                            },
                        },
                        {
                            value: 750,
                            name: 'Direct',
                            itemStyle: {
                                color: '#65d8cc',
                            },
                        },
                        {
                            value: 750,
                            name: 'Email',
                            itemStyle: {
                                color: '#313679',
                            },
                        },
                    ],
                },
            ],
        },
    },
    {
        type: 'BAR',
        option: {
            legend: {},
            tooltip: {},
            dataset: {
                source: [
                    ['product', '2015', '2016', '2017', '2018', '2019'],
                    ['Matcha Latte', 43.3, 85.8, 93.7, 81.3, 75],
                    ['Milk Tea', 83.1, 73.4, 55.1, 61, 24],
                ],
            },
            xAxis: { type: 'category' },
            yAxis: {},
            barWidth: 10,
            barGap: '90%',
            // Declare several bar series, each will be mapped
            // to a column of dataset.source by default.
            series: [
                {
                    type: 'bar',
                    itemStyle: {
                        color: '#313679',
                    },
                },
                {
                    type: 'bar',
                    itemStyle: {
                        color: '#65d8cc',
                    },
                },
                {
                    type: 'bar',
                    itemStyle: {
                        color: '#ffc600',
                    },
                },
                {
                    type: 'bar',
                    itemStyle: {
                        color: '#65d8cc',
                    },
                },
                {
                    type: 'bar',
                    itemStyle: {
                        color: '#ffc600',
                    },
                },
            ],
        },
    },
    {
        type: 'BAR3D',
        option: {
            legend: {},
            tooltip: {},
            dataset: {
                source: [
                    ['product', '2015', '2016', '2017', '2018', '2019'],
                    ['Matcha Latte', 43.3, 85.8, 93.7, 81.3, 75],
                    ['Milk Tea', 83.1, 73.4, 55.1, 61, 24],
                ],
            },
            xAxis: { type: 'category' },
            yAxis: {},
            barWidth: 10,
            barGap: '90%',
            // Declare several bar series, each will be mapped
            // to a column of dataset.source by default.
            series: [
                {
                    type: 'bar',
                    itemStyle: {
                        color: '#313679',
                    },
                },
                {
                    type: 'bar',
                    itemStyle: {
                        color: '#65d8cc',
                    },
                },
                {
                    type: 'bar',
                    itemStyle: {
                        color: '#ffc600',
                    },
                },
                {
                    type: 'bar',
                    itemStyle: {
                        color: '#65d8cc',
                    },
                },
                {
                    type: 'bar',
                    itemStyle: {
                        color: '#ffc600',
                    },
                },
            ],
        },
    },
]

export const tableData = {
    HEADER: [
        'CASENO',
        'DESCRIPTION',
        'CUSTOMERID',
        'CUSTOMERNAME',
        'USERCODE',
        'AMLUSERCODE',
        'AMLOUSERCODE',
        'MLROUSERCODE',
        'USERCOMMENTS',
        'AMLUSERCOMMENTS',
        'AMLOCOMMENTS',
        'MLROCOMMENTS',
        'USERTIMESTAMP',
        'AMLUSERTIMESTAMP',
        'AMLOTIMESTAMP',
        'MLROTIMESTAMP',
    ],
    DATA: [
        [
            '119955',
            null,
            '201077902',
            'K. K. BANSAL',
            'BranchUser',
            'AMLUSER',
            null,
            null,
            null,
            null,
            null,
            null,
            '26/09/2020',
            '26/09/2020',
            null,
            null,
        ],
        [
            '119948',
            null,
            '201077902',
            'K. K. BANSAL',
            'SYSTEM',
            'AMLUser',
            null,
            null,
            null,
            null,
            null,
            null,
            '07/08/2020',
            '07/08/2020',
            null,
            null,
        ],
        [
            '119863',
            null,
            '201077902',
            'K. K. BANSAL',
            'SYSTEM',
            'AMLUser',
            null,
            null,
            null,
            null,
            null,
            null,
            '08/05/2018',
            '08/05/2018',
            null,
            null,
        ],
        [
            '119863',
            null,
            '201077902',
            'K. K. BANSAL',
            'SYSTEM',
            'AMLUser',
            null,
            null,
            null,
            null,
            null,
            null,
            '08/05/2018',
            '08/05/2018',
            null,
            null,
        ],
        [
            '119863',
            null,
            '201077902',
            'K. K. BANSAL',
            'SYSTEM',
            'AMLUser',
            null,
            null,
            null,
            null,
            null,
            null,
            '08/05/2018',
            '08/05/2018',
            null,
            null,
        ],
        [
            '119863',
            null,
            '201077902',
            'K. K. BANSAL',
            'SYSTEM',
            'AMLUser',
            null,
            null,
            null,
            null,
            null,
            null,
            '08/05/2018',
            '08/05/2018',
            null,
            null,
        ],
        [
            '119863',
            null,
            '201077902',
            'K. K. BANSAL',
            'SYSTEM',
            'AMLUser',
            null,
            null,
            null,
            null,
            null,
            null,
            '08/05/2018',
            '08/05/2018',
            null,
            null,
        ],
        [
            '119863',
            null,
            '201077902',
            'K. K. BANSAL',
            'SYSTEM',
            'AMLUser',
            null,
            null,
            null,
            null,
            null,
            null,
            '08/05/2018',
            '08/05/2018',
            null,
            null,
        ],
        [
            '119863',
            null,
            '201077902',
            'K. K. BANSAL',
            'SYSTEM',
            'AMLUser',
            null,
            null,
            null,
            null,
            null,
            null,
            '08/05/2018',
            '08/05/2018',
            null,
            null,
        ],
        [
            '119863',
            null,
            '201077902',
            'K. K. BANSAL',
            'SYSTEM',
            'AMLUser',
            null,
            null,
            null,
            null,
            null,
            null,
            '08/05/2018',
            '08/05/2018',
            null,
            null,
        ],
        [
            '119863',
            null,
            '201077902',
            'K. K. BANSAL',
            'SYSTEM',
            'AMLUser',
            null,
            null,
            null,
            null,
            null,
            null,
            '08/05/2018',
            '08/05/2018',
            null,
            null,
        ],
        [
            '119863',
            null,
            '201077902',
            'K. K. BANSAL',
            'SYSTEM',
            'AMLUser',
            null,
            null,
            null,
            null,
            null,
            null,
            '08/05/2018',
            '08/05/2018',
            null,
            null,
        ],
        [
            '119863',
            null,
            '201077902',
            'K. K. BANSAL',
            'SYSTEM',
            'AMLUser',
            null,
            null,
            null,
            null,
            null,
            null,
            '08/05/2018',
            '08/05/2018',
            null,
            null,
        ],
        [
            '119863',
            null,
            '201077902',
            'K. K. BANSAL',
            'SYSTEM',
            'AMLUser',
            null,
            null,
            null,
            null,
            null,
            null,
            '08/05/2018',
            '08/05/2018',
            null,
            null,
        ],
        [
            '169863',
            null,
            '201077902',
            'K. K. BANSAL',
            'SYSTEM',
            'AMLUser',
            null,
            null,
            null,
            null,
            null,
            null,
            '08/05/2018',
            '08/05/2018',
            null,
            null,
        ],
        [
            '129863',
            null,
            '201077902',
            'K. K. BANSAL',
            'SYSTEM',
            'AMLUser',
            null,
            null,
            null,
            null,
            null,
            null,
            '08/05/2018',
            '08/05/2018',
            null,
            null,
        ],
        [
            '119263',
            null,
            '201077902',
            'K. K. BANSAL',
            'SYSTEM',
            'AMLUser',
            null,
            null,
            null,
            null,
            null,
            null,
            '08/05/2018',
            '08/05/2018',
            null,
            null,
        ],
        [
            '114863',
            null,
            '201077902',
            'K. K. BANSAL',
            'SYSTEM',
            'AMLUser',
            null,
            null,
            null,
            null,
            null,
            null,
            '08/05/2018',
            '08/05/2018',
            null,
            null,
        ],
        [
            '119863',
            null,
            '201077902',
            'K. K. BANSAL',
            'SYSTEM',
            'AMLUser',
            null,
            null,
            null,
            null,
            null,
            null,
            '08/05/2018',
            '08/05/2018',
            null,
            null,
        ],
        [
            '119863',
            null,
            '201077902',
            'K. K. BANSAL',
            'SYSTEM',
            'AMLUser',
            null,
            null,
            null,
            null,
            null,
            null,
            '08/05/2018',
            '08/05/2018',
            null,
            null,
        ],
        [
            '119863',
            null,
            '201077902',
            'K. K. BANSAL',
            'SYSTEM',
            'AMLUser',
            null,
            null,
            null,
            null,
            null,
            null,
            '08/05/2018',
            '08/05/2018',
            null,
            null,
        ],
        [
            '119863',
            null,
            '201077902',
            'K. K. BANSAL',
            'SYSTEM',
            'AMLUser',
            null,
            null,
            null,
            null,
            null,
            null,
            '08/05/2018',
            '08/05/2018',
            null,
            null,
        ],
        [
            '119863',
            null,
            '201077902',
            'K. K. BANSAL',
            'SYSTEM',
            'AMLUser',
            null,
            null,
            null,
            null,
            null,
            null,
            '08/05/2018',
            '08/05/2018',
            null,
            null,
        ],
        [
            '119863',
            null,
            '201077902',
            'K. K. BANSAL',
            'SYSTEM',
            'AMLUser',
            null,
            null,
            null,
            null,
            null,
            null,
            '08/05/2018',
            '08/05/2018',
            null,
            null,
        ],
        [
            '119863',
            null,
            '201077902',
            'K. K. BANSAL',
            'SYSTEM',
            'AMLUser',
            null,
            null,
            null,
            null,
            null,
            null,
            '08/05/2018',
            '08/05/2018',
            null,
            null,
        ],
        [
            '119863',
            null,
            '201077902',
            'K. K. BANSAL',
            'SYSTEM',
            'AMLUser',
            null,
            null,
            null,
            null,
            null,
            null,
            '08/05/2018',
            '08/05/2018',
            null,
            null,
        ],
        [
            '119863',
            null,
            '201077902',
            'K. K. BANSAL',
            'SYSTEM',
            'AMLUser',
            null,
            null,
            null,
            null,
            null,
            null,
            '08/05/2018',
            '08/05/2018',
            null,
            null,
        ],
        [
            '119863',
            null,
            '201077902',
            'K. K. BANSAL',
            'SYSTEM',
            'AMLUser',
            null,
            null,
            null,
            null,
            null,
            null,
            '08/05/2018',
            '08/05/2018',
            null,
            null,
        ],
        [
            '119863',
            null,
            '201077902',
            'K. K. BANSAL',
            'SYSTEM',
            'AMLUser',
            null,
            null,
            null,
            null,
            null,
            null,
            '08/05/2018',
            '08/05/2018',
            null,
            null,
        ],
        [
            '119863',
            null,
            '201077902',
            'K. K. BANSAL',
            'SYSTEM',
            'AMLUser',
            null,
            null,
            null,
            null,
            null,
            null,
            '08/05/2018',
            '08/05/2018',
            null,
            null,
        ],
        [
            '119863',
            null,
            '201077902',
            'K. K. BANSAL',
            'SYSTEM',
            'AMLUser',
            null,
            null,
            null,
            null,
            null,
            null,
            '08/05/2018',
            '08/05/2018',
            null,
            null,
        ],
        [
            '119863',
            null,
            '201077902',
            'K. K. BANSAL',
            'SYSTEM',
            'AMLUser',
            null,
            null,
            null,
            null,
            null,
            null,
            '08/05/2018',
            '08/05/2018',
            null,
            null,
        ],
        [
            '119863',
            null,
            '201077902',
            'K. K. BANSAL',
            'SYSTEM',
            'AMLUser',
            null,
            null,
            null,
            null,
            null,
            null,
            '08/05/2018',
            '08/05/2018',
            null,
            null,
        ],
        [
            '119863',
            null,
            '201077902',
            'K. K. BANSAL',
            'SYSTEM',
            'AMLUser',
            null,
            null,
            null,
            null,
            null,
            null,
            '08/05/2018',
            '08/05/2018',
            null,
            null,
        ],
        [
            '119863',
            null,
            '201077902',
            'K. K. BANSAL',
            'SYSTEM',
            'AMLUser',
            null,
            null,
            null,
            null,
            null,
            null,
            '08/05/2018',
            '08/05/2018',
            null,
            null,
        ],
        [
            '119863',
            null,
            '201077902',
            'K. K. BANSAL',
            'SYSTEM',
            'AMLUser',
            null,
            null,
            null,
            null,
            null,
            null,
            '08/05/2018',
            '08/05/2018',
            null,
            null,
        ],
        [
            '119863',
            null,
            '201077902',
            'K. K. BANSAL',
            'SYSTEM',
            'AMLUser',
            null,
            null,
            null,
            null,
            null,
            null,
            '08/05/2018',
            '08/05/2018',
            null,
            null,
        ],
        [
            '119863',
            null,
            '201077902',
            'K. K. BANSAL',
            'SYSTEM',
            'AMLUser',
            null,
            null,
            null,
            null,
            null,
            null,
            '08/05/2018',
            '08/05/2018',
            null,
            null,
        ],
        [
            '119863',
            null,
            '201077902',
            'K. K. BANSAL',
            'SYSTEM',
            'AMLUser',
            null,
            null,
            null,
            null,
            null,
            null,
            '08/05/2018',
            '08/05/2018',
            null,
            null,
        ],
        [
            '119863',
            null,
            '201077902',
            'K. K. BANSAL',
            'SYSTEM',
            'AMLUser',
            null,
            null,
            null,
            null,
            null,
            null,
            '08/05/2018',
            '08/05/2018',
            null,
            null,
        ],
        [
            '119863',
            null,
            '201077902',
            'K. K. BANSAL',
            'SYSTEM',
            'AMLUser',
            null,
            null,
            null,
            null,
            null,
            null,
            '08/05/2018',
            '08/05/2018',
            null,
            null,
        ],
        [
            '119863',
            null,
            '201077902',
            'K. K. BANSAL',
            'SYSTEM',
            'AMLUser',
            null,
            null,
            null,
            null,
            null,
            null,
            '08/05/2018',
            '08/05/2018',
            null,
            null,
        ],
        [
            '119863',
            null,
            '201077902',
            'K. K. BANSAL',
            'SYSTEM',
            'AMLUser',
            null,
            null,
            null,
            null,
            null,
            null,
            '08/05/2018',
            '08/05/2018',
            null,
            null,
        ],
    ],
}

export const graphDataTree = {
    TRANSACTIONRISK: "1",
    ENTITYICON: "I.png",
    children: [
      {
        TRANSACTIONRISK: "N.A.",
        LINKEDACCOUNTNO: "078908902",
        LINKEDNAME: "K. K. BANSAL",
        SEARCHACCOUNTNO: "078908902",
        IFEXISTINGTAB: "Level_1",
        ENTITYICON: "M",
        LINKEDCUSTOMERID: "201077902",
        FORCELINK: "Friends~testing forcelink",
        TRANSACTEDCOUNT: "N.A.",
        children: [],
        LINKEDTYPE: "M",
        LINKEDCUSTOMERTYPE: "I",
        name: "078908902",
        DUPLICATEVALUE: "N.A.",
        CUSTOMERRISK: "N.A.",
        TRANSACTEDAMOUNT: "N.A."
      },
      {
        TRANSACTIONRISK: "1",
        LINKEDACCOUNTNO: "50230100006865",
        LINKEDNAME: "RAM SINGH SO RAM PRATAP",
        levelName: "2",
        SEARCHACCOUNTNO: "078908902",
        IFEXISTINGTAB: "N.A.",
        ENTITYICON: "I.png",
        LINKEDCUSTOMERID: "610353203",
        FORCELINK: "None",
        TRANSACTEDCOUNT: "1",
        children: [
          {
            TRANSACTIONRISK: "N.A.",
            LINKEDACCOUNTNO: "50230100006865",
            LINKEDNAME: "RAM SINGH SO RAM PRATAP",
            SEARCHACCOUNTNO: "50230100006865",
            IFEXISTINGTAB: "Level_2",
            ENTITYICON: "M",
            LINKEDCUSTOMERID: "610353203",
            FORCELINK: "None",
            TRANSACTEDCOUNT: "N.A.",
            children: [],
            LINKEDTYPE: "M",
            LINKEDCUSTOMERTYPE: "I",
            name: "50230100006865",
            DUPLICATEVALUE: "N.A.",
            CUSTOMERRISK: "N.A.",
            TRANSACTEDAMOUNT: "N.A."
          },
          {
            TRANSACTIONRISK: "1",
            LINKEDACCOUNTNO: "019418817",
            LINKEDNAME: "JASVIR SINGH",
            levelName: "3",
            SEARCHACCOUNTNO: "50230100006865",
            IFEXISTINGTAB: "N.A.",
            ENTITYICON: "I.png",
            LINKEDCUSTOMERID: "31169005",
            FORCELINK: "None",
            TRANSACTEDCOUNT: "1",
            children: [
              {
                TRANSACTIONRISK: "1",
                LINKEDACCOUNTNO: "50230100008538",
                LINKEDNAME: "JAI SHRI KRISHNA S.H.G.",
                levelName: "4",
                SEARCHACCOUNTNO: "019418817",
                IFEXISTINGTAB: "N.A.",
                ENTITYICON: "I.png",
                LINKEDCUSTOMERID: "612926240",
                FORCELINK: "None",
                TRANSACTEDCOUNT: "1",
                children: [
                  {
                    TRANSACTIONRISK: "N.A.",
                    LINKEDACCOUNTNO: "50230100008538",
                    LINKEDNAME: "JAI SHRI KRISHNA S.H.G.",
                    SEARCHACCOUNTNO: "50230100008538",
                    IFEXISTINGTAB: "Level_4",
                    ENTITYICON: "M",
                    LINKEDCUSTOMERID: "612926240",
                    FORCELINK: "None",
                    TRANSACTEDCOUNT: "N.A.",
                    children: [],
                    LINKEDTYPE: "M",
                    LINKEDCUSTOMERTYPE: "I",
                    name: "50230100008538",
                    DUPLICATEVALUE: "N.A.",
                    CUSTOMERRISK: "N.A.",
                    TRANSACTEDAMOUNT: "N.A."
                  },
                  {
                    TRANSACTIONRISK: "1",
                    LINKEDACCOUNTNO: "50230100008353",
                    LINKEDNAME: "SHER BAHADUR S/O HARI LAL",
                    levelName: "5",
                    SEARCHACCOUNTNO: "50230100008538",
                    IFEXISTINGTAB: "N.A.",
                    ENTITYICON: "I.png",
                    LINKEDCUSTOMERID: "612578991",
                    FORCELINK: "None",
                    TRANSACTEDCOUNT: "1",
                    children: [
                      {
                        TRANSACTIONRISK: "N.A.",
                        LINKEDACCOUNTNO: "50230100008353",
                        LINKEDNAME: "SHER BAHADUR S/O HARI LAL",
                        SEARCHACCOUNTNO: "50230100008353",
                        IFEXISTINGTAB: "Level_5",
                        ENTITYICON: "M",
                        LINKEDCUSTOMERID: "612578991",
                        FORCELINK: "None",
                        TRANSACTEDCOUNT: "N.A.",
                        children: [],
                        LINKEDTYPE: "M",
                        LINKEDCUSTOMERTYPE: "I",
                        name: "50230100008353",
                        DUPLICATEVALUE: "N.A.",
                        CUSTOMERRISK: "N.A.",
                        TRANSACTEDAMOUNT: "N.A."
                      }
                    ],
                    LINKEDTYPE: "TRANSACTION",
                    LINKEDCUSTOMERTYPE: "I",
                    name: "50230100008353",
                    DUPLICATEVALUE: "N.A.",
                    CUSTOMERRISK: "N.A.",
                    TRANSACTEDAMOUNT: "1000000"
                  }
                ],
                LINKEDTYPE: "TRANSACTION",
                LINKEDCUSTOMERTYPE: "I",
                name: "50230100008538",
                DUPLICATEVALUE: "N.A.",
                CUSTOMERRISK: "N.A.",
                TRANSACTEDAMOUNT: "1000000"
              },
              {
                TRANSACTIONRISK: "1",
                LINKEDACCOUNTNO: "50230100002058",
                LINKEDNAME: "HANSH RAJ S/O SAHEB DEEN",
                levelName: "4",
                SEARCHACCOUNTNO: "019418817",
                IFEXISTINGTAB: "N.A.",
                ENTITYICON: "I.png",
                LINKEDCUSTOMERID: "610360699",
                FORCELINK: "None",
                TRANSACTEDCOUNT: "1",
                children: [
                  {
                    TRANSACTIONRISK: "N.A.",
                    LINKEDACCOUNTNO: "50230100002058",
                    LINKEDNAME: "HANSH RAJ S/O SAHEB DEEN",
                    SEARCHACCOUNTNO: "50230100002058",
                    IFEXISTINGTAB: "Level_4",
                    ENTITYICON: "M",
                    LINKEDCUSTOMERID: "610360699",
                    FORCELINK: "None",
                    TRANSACTEDCOUNT: "N.A.",
                    children: [],
                    LINKEDTYPE: "M",
                    LINKEDCUSTOMERTYPE: "I",
                    name: "50230100002058",
                    DUPLICATEVALUE: "N.A.",
                    CUSTOMERRISK: "N.A.",
                    TRANSACTEDAMOUNT: "N.A."
                  }
                ],
                LINKEDTYPE: "TRANSACTION",
                LINKEDCUSTOMERTYPE: "I",
                name: "50230100002058",
                DUPLICATEVALUE: "N.A.",
                CUSTOMERRISK: "N.A.",
                TRANSACTEDAMOUNT: "1000000"
              }
            ],
            LINKEDTYPE: "TRANSACTION",
            LINKEDCUSTOMERTYPE: "I",
            name: "019418817",
            DUPLICATEVALUE: "N.A.",
            CUSTOMERRISK: "N.A.",
            TRANSACTEDAMOUNT: "46635"
          }
        ],
        LINKEDTYPE: "TRANSACTION",
        LINKEDCUSTOMERTYPE: "I",
        name: "50230100006865",
        DUPLICATEVALUE: "N.A.",
        CUSTOMERRISK: "N.A.",
        TRANSACTEDAMOUNT: "1000000"
      },
      {
        TRANSACTIONRISK: "1",
        LINKEDACCOUNTNO: "076504509",
        LINKEDNAME: "ASHOK SINGH",
        levelName: "2",
        SEARCHACCOUNTNO: "078908902",
        IFEXISTINGTAB: "N.A.",
        ENTITYICON: "I.png",
        LINKEDCUSTOMERID: "200973429",
        FORCELINK: "Parents/Child~None",
        TRANSACTEDCOUNT: "1",
        children: [
          {
            TRANSACTIONRISK: "N.A.",
            LINKEDACCOUNTNO: "076504509",
            LINKEDNAME: "ASHOK SINGH",
            SEARCHACCOUNTNO: "076504509",
            IFEXISTINGTAB: "Level_2",
            ENTITYICON: "M",
            LINKEDCUSTOMERID: "200973429",
            FORCELINK: "None",
            TRANSACTEDCOUNT: "N.A.",
            children: [],
            LINKEDTYPE: "M",
            LINKEDCUSTOMERTYPE: "I",
            name: "076504509",
            DUPLICATEVALUE: "N.A.",
            CUSTOMERRISK: "N.A.",
            TRANSACTEDAMOUNT: "N.A."
          },
          {
            TRANSACTIONRISK: "1",
            LINKEDACCOUNTNO: "078908902",
            LINKEDNAME: "K. K. BANSAL",
            SEARCHACCOUNTNO: "076504509",
            IFEXISTINGTAB: "Level_1",
            ENTITYICON: "I.png",
            LINKEDCUSTOMERID: "201077902",
            FORCELINK: "Spouse~None",
            TRANSACTEDCOUNT: "1",
            children: [],
            LINKEDTYPE: "TRANSACTION",
            LINKEDCUSTOMERTYPE: "I",
            name: "078908902",
            DUPLICATEVALUE: "N.A.",
            CUSTOMERRISK: "N.A.",
            TRANSACTEDAMOUNT: "280000"
          }
        ],
        LINKEDTYPE: "TRANSACTION",
        LINKEDCUSTOMERTYPE: "I",
        name: "076504509",
        DUPLICATEVALUE: "N.A.",
        CUSTOMERRISK: "N.A.",
        TRANSACTEDAMOUNT: "1000000"
      },
      {
        TRANSACTIONRISK: "1",
        LINKEDACCOUNTNO: "50230100001859",
        LINKEDNAME: "RASTRIYE GRAMIN ROJGAR GARANTY YOJNA",
        levelName: "2",
        SEARCHACCOUNTNO: "078908902",
        IFEXISTINGTAB: "N.A.",
        ENTITYICON: "I.png",
        LINKEDCUSTOMERID: "610360430",
        FORCELINK: "None",
        TRANSACTEDCOUNT: "1",
        children: [
          {
            TRANSACTIONRISK: "N.A.",
            LINKEDACCOUNTNO: "50230100001859",
            LINKEDNAME: "RAM PRASAD MAURYA",
            SEARCHACCOUNTNO: "50230100001859",
            IFEXISTINGTAB: "Level_2",
            ENTITYICON: "A",
            LINKEDCUSTOMERID: "610360430",
            FORCELINK: "None",
            TRANSACTEDCOUNT: "N.A.",
            children: [],
            LINKEDTYPE: "A",
            LINKEDCUSTOMERTYPE: "I",
            name: "50230100001859",
            DUPLICATEVALUE: "N.A.",
            CUSTOMERRISK: "N.A.",
            TRANSACTEDAMOUNT: "N.A."
          },
          {
            TRANSACTIONRISK: "N.A.",
            LINKEDACCOUNTNO: "50230100001859",
            LINKEDNAME: "RASTRIYE GRAMIN ROJGAR GARANTY",
            SEARCHACCOUNTNO: "50230100001859",
            IFEXISTINGTAB: "Level_2",
            ENTITYICON: "M",
            LINKEDCUSTOMERID: "610360430",
            FORCELINK: "None",
            TRANSACTEDCOUNT: "N.A.",
            children: [],
            LINKEDTYPE: "M",
            LINKEDCUSTOMERTYPE: "I",
            name: "50230100001859",
            DUPLICATEVALUE: "N.A.",
            CUSTOMERRISK: "N.A.",
            TRANSACTEDAMOUNT: "N.A."
          },
          {
            TRANSACTIONRISK: "1",
            LINKEDACCOUNTNO: "019402076",
            LINKEDNAME: "RASTRIYE GRAMIN ROJGAR GARANTY",
            levelName: "3",
            SEARCHACCOUNTNO: "50230100001859",
            IFEXISTINGTAB: "N.A.",
            ENTITYICON: "I.png",
            LINKEDCUSTOMERID: "N.A.",
            FORCELINK: "Spouse~None",
            TRANSACTEDCOUNT: "2",
            children: [
              {
                TRANSACTIONRISK: "1",
                LINKEDACCOUNTNO: "50230100009161",
                LINKEDNAME: "DINESH KUMAR S/O KANDHAI RAM",
                levelName: "4",
                SEARCHACCOUNTNO: "019402076",
                IFEXISTINGTAB: "N.A.",
                ENTITYICON: "I.png",
                LINKEDCUSTOMERID: "613379766",
                FORCELINK: "None",
                TRANSACTEDCOUNT: "1",
                children: [
                  {
                    TRANSACTIONRISK: "N.A.",
                    LINKEDACCOUNTNO: "50230100009161",
                    LINKEDNAME: "DINESH KUMAR S/O KANDHAI RAM",
                    SEARCHACCOUNTNO: "50230100009161",
                    IFEXISTINGTAB: "Level_4",
                    ENTITYICON: "M",
                    LINKEDCUSTOMERID: "613379766",
                    FORCELINK: "None",
                    TRANSACTEDCOUNT: "N.A.",
                    children: [],
                    LINKEDTYPE: "M",
                    LINKEDCUSTOMERTYPE: "I",
                    name: "50230100009161",
                    DUPLICATEVALUE: "N.A.",
                    CUSTOMERRISK: "N.A.",
                    TRANSACTEDAMOUNT: "N.A."
                  },
                  {
                    TRANSACTIONRISK: "1",
                    LINKEDACCOUNTNO: "0112561269",
                    LINKEDNAME: "DINESH KUMAR S/O KANDHAI RAM",
                    levelName: "5",
                    SEARCHACCOUNTNO: "50230100009161",
                    IFEXISTINGTAB: "N.A.",
                    ENTITYICON: "I.png",
                    LINKEDCUSTOMERID: "N.A.",
                    FORCELINK: "None",
                    TRANSACTEDCOUNT: "1",
                    children: [
                      {
                        TRANSACTIONRISK: "1",
                        LINKEDACCOUNTNO: "50230100003802",
                        LINKEDNAME: "DEOKI DO RAMRAJ",
                        levelName: "6",
                        SEARCHACCOUNTNO: "0112561269",
                        IFEXISTINGTAB: "N.A.",
                        ENTITYICON: "I.png",
                        LINKEDCUSTOMERID: "610355390",
                        FORCELINK: "None",
                        TRANSACTEDCOUNT: "1",
                        children: [
                          {
                            TRANSACTIONRISK: "N.A.",
                            LINKEDACCOUNTNO: "50230100003802",
                            LINKEDNAME: "DEOKI DO RAMRAJ",
                            SEARCHACCOUNTNO: "50230100003802",
                            IFEXISTINGTAB: "Level_6",
                            ENTITYICON: "M",
                            LINKEDCUSTOMERID: "610355390",
                            FORCELINK: "None",
                            TRANSACTEDCOUNT: "N.A.",
                            children: [],
                            LINKEDTYPE: "M",
                            LINKEDCUSTOMERTYPE: "I",
                            name: "50230100003802",
                            DUPLICATEVALUE: "N.A.",
                            CUSTOMERRISK: "N.A.",
                            TRANSACTEDAMOUNT: "N.A."
                          }
                        ],
                        LINKEDTYPE: "TRANSACTION",
                        LINKEDCUSTOMERTYPE: "I",
                        name: "50230100003802",
                        DUPLICATEVALUE: "N.A.",
                        CUSTOMERRISK: "N.A.",
                        TRANSACTEDAMOUNT: "1000000"
                      },
                      {
                        TRANSACTIONRISK: "1",
                        LINKEDACCOUNTNO: "50230100007906",
                        LINKEDNAME: "NAVAL KISHOR TRIVEDI S/O SHIV JIYAWAN TIWARI",
                        levelName: "6",
                        SEARCHACCOUNTNO: "0112561269",
                        IFEXISTINGTAB: "N.A.",
                        ENTITYICON: "I.png",
                        LINKEDCUSTOMERID: "610357842",
                        FORCELINK: "None",
                        TRANSACTEDCOUNT: "1",
                        children: [
                          {
                            TRANSACTIONRISK: "N.A.",
                            LINKEDACCOUNTNO: "50230100007906",
                            LINKEDNAME: "NAVAL KISHOR TRIVEDI S/O SHIV",
                            SEARCHACCOUNTNO: "50230100007906",
                            IFEXISTINGTAB: "Level_6",
                            ENTITYICON: "M",
                            LINKEDCUSTOMERID: "610357842",
                            FORCELINK: "None",
                            TRANSACTEDCOUNT: "N.A.",
                            children: [],
                            LINKEDTYPE: "M",
                            LINKEDCUSTOMERTYPE: "I",
                            name: "50230100007906",
                            DUPLICATEVALUE: "N.A.",
                            CUSTOMERRISK: "N.A.",
                            TRANSACTEDAMOUNT: "N.A."
                          },
                          {
                            TRANSACTIONRISK: "1",
                            LINKEDACCOUNTNO: "50230300001741",
                            LINKEDNAME: "PHOOL KALI WO RAMA NAND",
                            levelName: "7",
                            SEARCHACCOUNTNO: "50230100007906",
                            IFEXISTINGTAB: "N.A.",
                            ENTITYICON: "I.png",
                            LINKEDCUSTOMERID: "610351913",
                            FORCELINK: "None",
                            TRANSACTEDCOUNT: "1",
                            children: [
                              {
                                TRANSACTIONRISK: "N.A.",
                                LINKEDACCOUNTNO: "50230300001741",
                                LINKEDNAME: "PHOOL KALI WO RAMA NAND",
                                SEARCHACCOUNTNO: "50230300001741",
                                IFEXISTINGTAB: "Level_7",
                                ENTITYICON: "M",
                                LINKEDCUSTOMERID: "610351913",
                                FORCELINK: "None",
                                TRANSACTEDCOUNT: "N.A.",
                                children: [],
                                LINKEDTYPE: "M",
                                LINKEDCUSTOMERTYPE: "I",
                                name: "50230300001741",
                                DUPLICATEVALUE: "N.A.",
                                CUSTOMERRISK: "N.A.",
                                TRANSACTEDAMOUNT: "N.A."
                              },
                              {
                                TRANSACTIONRISK: "1",
                                LINKEDACCOUNTNO: "50230100001886",
                                LINKEDNAME: "LAXMI DEVI D/O RAM KUMAR MISHRA",
                                levelName: "8",
                                SEARCHACCOUNTNO: "50230300001741",
                                IFEXISTINGTAB: "N.A.",
                                ENTITYICON: "I.png",
                                LINKEDCUSTOMERID: "610360465",
                                FORCELINK: "None",
                                TRANSACTEDCOUNT: "1",
                                children: [
                                  {
                                    TRANSACTIONRISK: "N.A.",
                                    LINKEDACCOUNTNO: "50230100001886",
                                    LINKEDNAME: "LAXMI DEVI D/O RAM KUMAR MISHR",
                                    SEARCHACCOUNTNO: "50230100001886",
                                    IFEXISTINGTAB: "Level_8",
                                    ENTITYICON: "M",
                                    LINKEDCUSTOMERID: "610360465",
                                    FORCELINK: "None",
                                    TRANSACTEDCOUNT: "N.A.",
                                    children: [],
                                    LINKEDTYPE: "M",
                                    LINKEDCUSTOMERTYPE: "I",
                                    name: "50230100001886",
                                    DUPLICATEVALUE: "N.A.",
                                    CUSTOMERRISK: "N.A.",
                                    TRANSACTEDAMOUNT: "N.A."
                                  },
                                  {
                                    TRANSACTIONRISK: "1",
                                    LINKEDACCOUNTNO: "50230100001071",
                                    LINKEDNAME: "RAM DEV S/O JHURI",
                                    levelName: "9",
                                    SEARCHACCOUNTNO: "50230100001886",
                                    IFEXISTINGTAB: "N.A.",
                                    ENTITYICON: "I.png",
                                    LINKEDCUSTOMERID: "610359459",
                                    FORCELINK: "None",
                                    TRANSACTEDCOUNT: "1",
                                    children: [
                                      {
                                        TRANSACTIONRISK: "N.A.",
                                        LINKEDACCOUNTNO: "50230100001071",
                                        LINKEDNAME: "RAM DEV S/O JHURI",
                                        SEARCHACCOUNTNO: "50230100001071",
                                        IFEXISTINGTAB: "Level_9",
                                        ENTITYICON: "M",
                                        LINKEDCUSTOMERID: "610359459",
                                        FORCELINK: "None",
                                        TRANSACTEDCOUNT: "N.A.",
                                        children: [],
                                        LINKEDTYPE: "M",
                                        LINKEDCUSTOMERTYPE: "I",
                                        name: "50230100001071",
                                        DUPLICATEVALUE: "N.A.",
                                        CUSTOMERRISK: "N.A.",
                                        TRANSACTEDAMOUNT: "N.A."
                                      }
                                    ],
                                    LINKEDTYPE: "TRANSACTION",
                                    LINKEDCUSTOMERTYPE: "I",
                                    name: "50230100001071",
                                    DUPLICATEVALUE: "N.A.",
                                    CUSTOMERRISK: "N.A.",
                                    TRANSACTEDAMOUNT: "1000000"
                                  }
                                ],
                                LINKEDTYPE: "TRANSACTION",
                                LINKEDCUSTOMERTYPE: "I",
                                name: "50230100001886",
                                DUPLICATEVALUE: "N.A.",
                                CUSTOMERRISK: "N.A.",
                                TRANSACTEDAMOUNT: "1000000"
                              }
                            ],
                            LINKEDTYPE: "TRANSACTION",
                            LINKEDCUSTOMERTYPE: "I",
                            name: "50230300001741",
                            DUPLICATEVALUE: "N.A.",
                            CUSTOMERRISK: "N.A.",
                            TRANSACTEDAMOUNT: "1000000"
                          }
                        ],
                        LINKEDTYPE: "TRANSACTION",
                        LINKEDCUSTOMERTYPE: "I",
                        name: "50230100007906",
                        DUPLICATEVALUE: "N.A.",
                        CUSTOMERRISK: "N.A.",
                        TRANSACTEDAMOUNT: "1000000"
                      }
                    ],
                    LINKEDTYPE: "TRANSACTION",
                    LINKEDCUSTOMERTYPE: "I",
                    name: "0112561269",
                    DUPLICATEVALUE: "N.A.",
                    CUSTOMERRISK: "N.A.",
                    TRANSACTEDAMOUNT: "190298"
                  }
                ],
                LINKEDTYPE: "TRANSACTION",
                LINKEDCUSTOMERTYPE: "I",
                name: "50230100009161",
                DUPLICATEVALUE: "N.A.",
                CUSTOMERRISK: "N.A.",
                TRANSACTEDAMOUNT: "1000000"
              }
            ],
            LINKEDTYPE: "TRANSACTION",
            LINKEDCUSTOMERTYPE: "I",
            name: "019402076",
            DUPLICATEVALUE: "N.A.",
            CUSTOMERRISK: "N.A.",
            TRANSACTEDAMOUNT: "54636"
          },
          {
            TRANSACTIONRISK: "1",
            LINKEDACCOUNTNO: "50230200000031",
            LINKEDNAME: "SOMVANSHI HUME PAIP INDUSTREEJ JHAKRASI",
            levelName: "3",
            SEARCHACCOUNTNO: "50230100001859",
            IFEXISTINGTAB: "N.A.",
            ENTITYICON: "I.png",
            LINKEDCUSTOMERID: "613183398",
            FORCELINK: "None",
            TRANSACTEDCOUNT: "1",
            children: [
              {
                TRANSACTIONRISK: "N.A.",
                LINKEDACCOUNTNO: "50230200000031",
                LINKEDNAME: "SOMVANSHI HUME PAIP INDUSTREEJ JHAKRASI",
                SEARCHACCOUNTNO: "50230200000031",
                IFEXISTINGTAB: "Level_3",
                ENTITYICON: "M",
                LINKEDCUSTOMERID: "613183398",
                FORCELINK: "None",
                TRANSACTEDCOUNT: "N.A.",
                children: [],
                LINKEDTYPE: "M",
                LINKEDCUSTOMERTYPE: "I",
                name: "50230200000031",
                DUPLICATEVALUE: "N.A.",
                CUSTOMERRISK: "N.A.",
                TRANSACTEDAMOUNT: "N.A."
              }
            ],
            LINKEDTYPE: "TRANSACTION",
            LINKEDCUSTOMERTYPE: "I",
            name: "50230200000031",
            DUPLICATEVALUE: "N.A.",
            CUSTOMERRISK: "N.A.",
            TRANSACTEDAMOUNT: "1000000"
          }
        ],
        LINKEDTYPE: "TRANSACTION",
        LINKEDCUSTOMERTYPE: "I",
        name: "50230100001859",
        DUPLICATEVALUE: "N.A.",
        CUSTOMERRISK: "N.A.",
        TRANSACTEDAMOUNT: "1000000"
      }
    ],
    LINKEDTYPE: "TRANSACTION",
    name: "078908902",
    levelName: "1",
    CUSTOMERRISK: "N.A."
  }